// <auto-generated />
namespace Base.Data1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ist_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ist_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202410121915561_ist_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
